[package]
name = "hello_morphing"
version = "0.1.0"
edition = "2025"

[dependencies]
morphing-builtins = { path = "../../morphing-builtins" }
morphing-core = { path = "../../morphing-core" }
nalgebra = "0.33.2"
